### ISSUE TITLE
dependencies when an ancestor is found, but not the item, are unstacked

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#101]
When Eunice automatically unstacks independent items that are in the same level, it preserves levels when dependencies are item found, but not when only an ancestor of the dependency was found.

The following would be inappropriately unstacked:
```yaml
- - id: item1
    dependsUpon:
      id: item2
      items: missing
- - item2
```
