### ISSUE TITLE
dependency with items will not resolve inside a dependency permeable parent/ancestors

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#105]
If a dependency specifies an identifier and items, the items will not be resolved if it has a dependency permeable parent and/or ancestors.

```YAML
id: parent
items:
  - id: first
    dependsUpon:
      id: parent
      items: child
  - id: second
    dependencyPermeable: true
    items: child
```
