### ISSUE TITLE
infer stacks does not check descendants for depends upon in different levels

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#111]
Infer stacks introduced in #109 won't recognise in the following example that the third item needs to be in a level lower than second:

```yaml
- id: first
  dependsUpon: second
- id: second
  items:
    id: child of second
    dependsUpon: third
- third
```

So the following stack is inferred, with second and third in the same level regardless of the dependency from child of second onto third:

```yaml
- - id: first
    dependsUpon: second
- - id: second
    items:
      id: child of second
      dependsUpon: third
  - third
```

Instead of the following:

```yaml
- - id: first
    dependsUpon: second
- - id: second
    items:
      id: child of second
      dependsUpon: third
- - third
```
