### ISSUE TITLE
infer stacks doesn't recognise dependencies that go through an ancestor

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#112]
Infer stacks introduced in #109 only recognises dependencies that are within the stack. However, if dependencies within the stack unnecessarily specify the parent or a deeper ancestor they aren't recognised.

The following should stack first above second but doesn't:
```yaml
id: grandparent
items:
  id: parent
  items:
    - id: first
      dependsUpon:
        id: grandparent
        items:
          id: parent
          items: second
    - second
```
