### ISSUE TITLE
module imports with bindings named after the file are unnecessary verbosity

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#114]
Preserving JavaScript module imports of files that have the same name as the import's binding don't add any functionality and make reading Eunice YAML more difficult.

For example, the following JavaScript:
```javascript
import attributes from './attributes';
```
produces the following YAML
```yaml
id: attributes
type: import
dependsUpon: attributes
```

Item such as these could be removed entirely, as exports and variables already are.
