### ISSUE TITLE
default exports are no longer removed after #114

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#115]
Default exports are given the name of the file that contains them. Previously they were removed when they had no additional properties.

```yaml
- - id: App
    type: export
    dependsUpon: App
- - id: App
```

Changes made for issue #114 "module imports with bindings named after the file are unnecessary verbosity" bought together removal of exports, imports and variables into a single operation, but it also moved that operation before the one that gave the export the name of its parent file. This meant when the removal operation was executed the YAML was as follows and so not removed:

```yaml
- - type: export
    dependsUpon: App
- - id: App
```
