### ISSUE TITLE
top down file order does not move imports to the bottom

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#118]
When the JavaScript default to reverse file content is overridden, imports have the same stack position as they do in the source code:

```javascript
import imported from "module";

function functionDeclaration() {
	imported();
}
```

```yaml
- - id: imported
    type: import
    dependsUpon: module
- - id: functionDeclaration
    dependsUpon: imported
```

They should be moved to the bottom, as parameters and variables already are:

```yaml
- - id: functionDeclaration
    dependsUpon: imported
- - id: imported
    type: import
    dependsUpon: module
```
