### ISSUE TITLE
imports that extend classes are ignored

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#123]
When a JavaScript class is extends another and the base is an import, that import is ignored.
```javascript
import imported from "module";
class Class extends imported { }
```
is currently just returning
```yaml
- id: Class
  dependsUpon: imported
```
instead of including the import
```yaml
- - id: Class
    dependsUpon: imported
- - id: imported
    type: import
    dependsUpon: module
```
