### ISSUE TITLE
ignore anonymous types

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#130]
References to properties of C# anonymous types are included as dependencies with parents that have an empty id.

```csharp
using System;

class Class {
  void Method() {
    var variable = new { Property = "" };
  }
}
```
current:
```yaml
- id: TestCase
  items:
    id: DeclarationClass
    items:
      id: Method
      dependsUpon:
        id: TestCase
        items:
          id: 
          items: Property
```

Dependencies on anonymous types must not be included as dependencies within methods aren't currently supported. Also an id key with no value is invalid Eunice YAML.
