### ISSUE TITLE
support C# 8.0 static local functions

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#180]
Version 8.0 of C# added static local functions. Issue #179 added support for C# 8.0; however, Eunice doesn't seem to analyse code using this feature correctly. Child items aren't being created for the static local functions and dependencies on the static local functions have an extra item in the dependency hierarchy with no value for `id`.

**Comment by grahamdyson** [comment]
Added unit test for a static local function and the issue must be something more specific.
Found when analysing:
https://github.com/space-wizards/space-station-14/blob/31b2c9f8309d1961a62d7fa60aaa9a9d7246c7c0/Content.IntegrationTests/Tests/Body/SaveLoadReparentTest.cs#L97
output was:
```yaml
- id: SaveLoadReparentTest
  dependsUpon:
    # ...
    - id: Test
      items:
        id: 
        items:
          id: EnumerateQueryEnumerator
          items: TComp
```
