### ISSUE TITLE
first item in a multi-item level has no line feed in YAML

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/Eunice#37]
Currently the first item in a levels with multiple items is written in YAML with both the level sequence dash and the first items map dash on the same line.

```YAML
- - item1
  - item2
```

```YAML
- - id: item1
    keyOfItem1: valueOfItem1
  - item2
```

This makes it harder to distinguish between the contents of the first item and the other items in the level.

For example, fold/unfold in a YAML editor will usually be performed on a line. So the fold/unfold can only be performed on both the contents of first item and the other items in the level.

Having a line break after the first level sequence dash avoids this problem.

```YAML
-
  - item1
  - item2
```

```YAML
-
  - id: item1
    keyOfItem1: valueOfItem1
  - item2
```
