### ISSUE TITLE
dependency list doesn't show missing depends upon when ancestor found

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#89]
Dependency lists do not show dependencies when descendent not found, but one of its ancestor was.

The following example does list when selecting dependents of "parent", but does not list when selecting dependencies/depends upon of "dependent".

```YAML
- id: dependent
  dependsUpon:
    id: parent
    items: missing child
- parent
```

This behaviour was added to dependency counts in issue #51
