### ISSUE TITLE
fields of function arrow or expression

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#91]
In JavaScript functions can be assigned to class fields. I'm seeing examples of this is being used with arrow functions to get a more terse syntax compared to methods:

```javascript
class Class {
	method = () => called()
}
```

Eunice does not currently associate these functions with the class and the field name. In the example above, Eunice doesn't currently include an item for "method" and it doesn't add the dependency on "called" in that item, or even in the class:

```yaml
dependsUpon: called
items: Class
```

The expected YAML would be:

```yaml
items:
  id: Class
  items:
    id: method
    dependsUpon: called
```
