### ISSUE TITLE
dependencies in class fields associated with class parent

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#92]
Calls inside classes that are assigned to fields are being added as dependencies from the classes parent:

```javascript
class Class { field = called(); }
```
```yaml
dependsUpon: called
items: Class
```

The dependency would be more accurate if it was associated with the class, or even more so with the field:
```yaml
- id: Class
  items:
    id: field
    dependsUpon: called
```
