### ISSUE TITLE
remove self dependent exports

### ISSUE THREAD

**Issue by grahamdyson** [DevSnicket/eunice#97]
When there is both a declaration and an exports of the declaration, two items with same name are created.

```javascript
function functionDeclaration() { called(); }
export functionDeclaration;
```
```yaml
- - id: functionDeclaration
    items: called
- - id: functionDeclaration
    type: export
    dependsUpon: functionDeclaration
```

It would be easier to understand in Eunice if both items were consolidated:

```yaml
- - id: functionDeclaration
    type: export
    items: called
```
